### ISSUE TITLE
Where is the plugin.yml?

### ISSUE THREAD

**Issue by AdversariusPE** [PEMapModder/HereAuth#7]
Where is the plugin.yml? It's not working without them!

**Comment by PEMapModder** [comment]
This plugin uses the NOWHERE framework. It is compiled without directly creating a plugin.yml file first.
You cannot load this plugin from source using DevTools, or compile this plugin through ConsoleScript or pmt.mcpe.me; you must run the `compile.php` at the main directory of the repo with PHP 7, or simply download a phar build from the `compile/` directory.

In simple words, there is no and will never be a plugin.yml file in this plugin because it doesn't need one (directly).
